server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:${MYSQL_PORT:3307}/usuarios
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"